# Code generated by Claude
#
# Prompt:
#
# I want to learn about vibe coding. How can I code a hello world web app in python?
#
# Use python
# Use flask
#

from flask import Flask

# Create a Flask application instance
app = Flask(__name__)

# Define a route for the home page
@app.route('/')
def hello_world():
    return '<h1>Hello, World!</h1><p>Some text goes here.</p>'

# Define an additional route with a parameter
@app.route('/hello/<name>')
def hello_name(name):
    return f'<h1>Hello, {name}!</h1><p>Nice to meet you!</p>'

# Run the application
if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)